### ISSUE TITLE
ngAutodisable doesn't work when form is inside element with ngIf directive

### ISSUE THREAD

**Issue by Costo** [kirstein/angular-autodisable#10]
If the `<form ng-autodisable>` element is inside a `<div ng-if='true'>` element, then the button is not disabled when submitting the form.

See repro:
http://plnkr.co/edit/0LDH2n5HxzEJALZ8lLZ0?p=preview

**Comment by mburgosh** [comment]
This is related to the PR#5 find by attire value is not supported by jqLite, if you add jQuery to your dependencies this should work.

**Comment by mburgosh** [comment]
The proposed PR is outdated for the new approach since 0.2.0. Plus it proposes loping through the elements, which might not be the most effective.
see: https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll

**Comment by 23tux** [comment]
+1
I think this is also related to https://github.com/kirstein/angular-autodisable/pull/11. In my case, the PR solves the problem.

**Comment by 23tux** [comment]
Anything new on this issue? Is there a quick workaround?
