### ISSUE TITLE
need to config when to disable.

### ISSUE THREAD

**Issue by hxlniada** [kirstein/angular-autodisable#16]
when I submit a form in $modal(with animation: true), if I click very fast, the form will submit twice.
Because when the promise is done, the disabled is set to false, but the animation is not completed, I can still submit the form if I click very fast.
so, I want to config when to set disable to false.
In this scenorio, I want just when the promise is success, I set the disable to fase.

**Comment by mburgosh** [comment]
The best approach would be to delay the promise resolution to when you are actually want it to be done.

**Comment by hxlniada** [comment]
@mburgosh ok
