### ISSUE TITLE
$event is rewriten by ng-autodisable

### ISSUE THREAD

**Issue by hxlniada** [kirstein/angular-autodisable#17]
http://jsfiddle.net/wXnks/13/
You can see in the console
the event is not an object anymore
it's a 'click' string

**Comment by mburgosh** [comment]
I can't seem to get your example to work. Maybe you could isolate the issue a bit more?

From what I understand this would be an issue of the $event being parsed to string when parsing the ng-click value: https://github.com/kirstein/angular-autodisable/blob/master/angular-autodisable.js#L98
If this is the case, I'm not sure what can be done to solve this.

**Comment by stnor** [comment]
I believe the issue is that the $event is parsed fine, but the autodisable directive passes on only the event name 'click' rather than the actual event to my code, which breaks the contract.
