### ISSUE TITLE
Click event registered on forms

### ISSUE THREAD

**Issue by benfoster** [kirstein/angular-autodisable#8]
When using the directive with forms it looks like a click event is being registered. When I click into my form, the `ng-submit` handler is invoked.

My HTML:

```
      <form name="formMenuItem" ng-submit="vm.saveMenuItem()" ng-autodisable>
        <button class="btn btn-primary" type="submit" ng-disabled="formMenuItem.$invalid">
          <span ng-if="vm.menuItem.id">Add Menu Item</span>
          <i class="icon icon-tick"></i>
        </button>
      </form>
```

Controller:

```
    function saveMenuItem() {
      return vm.menuItem.id ? updateMenuItem() : addMenuItem();
    }

    function addMenuItem() {
      return menuService.addMenuItem(menu, vm.menuItem).then(function (mi) {
        menu.items.push(mi);
        notify.success('Menu Item added successfully.');
        resetMenuItemForm();
      });
    }
```

**Comment by benfoster** [comment]
After further investigation the issue is when using `ng-autodisable` on multiple elements on the same page (e.g. on a form and a buttton).

Repro: http://plnkr.co/edit/K0mCLcMKp3ElG4KaFXO4?p=preview

**Comment by mburgosh** [comment]
Thanks for the demo. I'm not using the form feature that much. But I'll look into this.

**Comment by kirstein** [comment]
@mburgosh the issue there is that we are overriding hoisted `ELEMENT` and `TYPE`. Are you currently fixing this or shall I?

**Comment by mburgosh** [comment]
I saw that. If you have time now do it. If not I can look into it tonight.

**Comment by mburgosh** [comment]
LOADING_CLASS might be affected as well.

**Comment by kirstein** [comment]
We need to hit it with the good ol' refactoring hammer. Working on it now, hopefully I am able to get a PR out soon.

**Comment by mburgosh** [comment]
Was thinking of a factory that returns an instance with the needed functions and attributes.

**Comment by mburgosh** [comment]
Some significant changes proposed. Please comment.

**Comment by kirstein** [comment]
@mburgosh can you make a pr please. Also sorry, I have had connectivity problems for the past few days.

**Comment by kirstein** [comment]
fixed with https://github.com/kirstein/angular-autodisable/pull/9.

Thank you guys.
